ci_cd_workflow = """\
name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Позволяет запускать процесс вручную

jobs:
  build:
    runs-on: ubuntu-latest  # Выбираем ОС

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Клонируем репозиторий

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Run tests
        run: mvn test

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packaged-app
          path: target/*.jar
"""

# Сохраняем обновленный CI/CD workflow в файле
ci_file_path = os.path.join(extract_path, "GitAction/.github/workflows/ci.yml")
os.makedirs(os.path.dirname(ci_file_path), exist_ok=True)

with open(ci_file_path, "w") as ci_file:
    ci_file.write(ci_cd_workflow)

# Подтверждаем путь к обновленному файлу
ci_file_path
